const CARD_ACTIONS = Object.freeze({
  SET_WIDTH: 'SET_WIDTH',
  SET_HEIGHT: 'SET_HEIGHT',
  RESET_CARD_SIZE: 'RESET_CARD_SIZE',
  SET_ROUND: 'SET_ROUND',
  SET_IMAGE_URL: 'SET_IMAGE_URL',
  TOGGLE_OUTLINE_MODE: 'TOGGLE_OUTLINE_MODE',
})

export default CARD_ACTIONS